/* global React, ReactDOM, Nav, Footer, useReveal */

function LegalLayout({ eyebrow, title, lastUpdated, children }) {
  return (
    <section className="legal-page">
      <div className="container legal-container">
        <a className="case-back" href="index.html">← Back to Zinely</a>
        <span className="legal-eyebrow">{eyebrow}</span>
        <h1 className="legal-h">{title}</h1>
        <p className="legal-meta">Last updated · {lastUpdated}</p>
        <div className="legal-prose">{children}</div>
      </div>
    </section>
  );
}

// ─── Terms of Service ─────────────────────────────────────────────────
function TermsOfService() {
  return (
    <LegalLayout eyebrow="Legal" title="Terms and Conditions" lastUpdated="27 April 2026">
      <p>
        These Terms govern your use of the chatting agency services provided by Zinely
        ("Zinely", "we", "our"). By engaging Zinely — whether as a creator, an applicant,
        or any other counterparty — you agree to be bound by these Terms.
      </p>

      <h2>1 · Who we are</h2>
      <p>
        Zinely operates as a chatting agency for adult content creators on platforms
        including OnlyFans, Fanvue, Fansly, LoyalFans, Fanfix and similar. We provide
        trained chatters, account management, and revenue-optimisation services on
        behalf of creators who engage us.
      </p>

      <h2>2 · Eligibility</h2>
      <ul>
        <li>You must be at least 18 years old to engage Zinely's services.</li>
        <li>You confirm that you are the lawful owner of the creator account or accounts you ask us to manage, or that you have explicit written authority to engage Zinely on behalf of the account owner.</li>
        <li>You confirm that all content uploaded to managed accounts complies with the rules of the underlying platform, applicable laws in your jurisdiction, and any age-verification or 2257-style documentation requirements.</li>
      </ul>

      <h2>3 · Scope of services</h2>
      <p>
        Zinely's services may include, depending on the package agreed in writing:
        live chatting (including PPV upselling, tip extraction, and fan retention),
        full account management, content scheduling, mass-message campaigns,
        pricing strategy, and chatter training. The exact deliverables, hours of
        coverage, and team composition are set out in your individual engagement.
      </p>

      <h2>4 · Account access &amp; security</h2>
      <ul>
        <li>You grant Zinely the access required to perform the agreed services. Where the underlying platform supports it, we use platform-approved chatter access. Where it does not, credentials are stored in a controlled vault with rotating sessions, IP whitelisting, and full audit logs.</li>
        <li>Every Zinely chatter signs a non-disclosure agreement before touching your account.</li>
        <li>You may revoke Zinely's access at any time. Once revoked, our active engagement on the account ends immediately.</li>
        <li>Zinely will not knowingly impersonate you outside the bounds of the chatter persona that you have approved in writing.</li>
      </ul>

      <h2>5 · Pricing &amp; payment</h2>
      <ul>
        <li><strong>Free 3-day trial.</strong> New creators may engage Zinely for an initial 3-day period at no charge, with full 24/7 chatting coverage included. You keep 100% of revenue generated during the trial. No card on file is required.</li>
        <li><strong>Performance.</strong> After the trial, Zinely's standard fee is between 20% and 26% of gross earnings on managed accounts, scaled to account volume. The exact rate is confirmed in writing before any commission becomes payable.</li>
        <li><strong>Hybrid.</strong> Higher-volume engagements may opt into a hybrid arrangement combining a smaller commission with a fixed monthly retainer.</li>
        <li>Invoices are issued monthly in arrears and are payable within seven (7) days of issue. Late payment may, at our discretion, result in suspension of services.</li>
      </ul>

      <h2>6 · Term &amp; cancellation</h2>
      <p>
        Engagements with Zinely are month-to-month. Either party may end the engagement
        at any time, with no notice period and no cancellation fee. On termination, any
        accrued fees up to the termination date remain payable.
      </p>

      <h2>7 · Confidentiality</h2>
      <p>
        Zinely treats all creator-account information, performance data, fan lists, and
        creative assets as strictly confidential. We will not share, sell, or repurpose
        any creator-specific data except where required by law or to deliver the agreed
        service.
      </p>

      <h2>8 · Intellectual property</h2>
      <p>
        All content and intellectual property uploaded to or generated by your account
        remains your property. Zinely claims no ownership over creator content. Where
        Zinely produces materials specifically for you (e.g. PPV scripts, drop calendars,
        analytics reports), you receive a perpetual licence to use those materials in
        connection with your account.
      </p>

      <h2>9 · Compliance</h2>
      <p>
        You are responsible for the lawfulness of the content on your account, for all
        platform-side compliance (including 2257 records or local equivalents), and for
        any tax obligations arising from your earnings. Zinely will operate within the
        rules of the underlying platforms and will not knowingly contravene them.
      </p>

      <h2>10 · Liability</h2>
      <p>
        Zinely's total aggregate liability to you in any twelve-month period is limited
        to the fees paid by you to Zinely in that same period. Zinely is not liable for
        loss of profit, loss of opportunity, platform-side account actions outside our
        control, or for any indirect or consequential loss.
      </p>

      <h2>11 · Chatter applicants</h2>
      <p>
        Information submitted via the apply flow at <a href="apply.html">/apply</a> is
        used solely to assess fit for chatter roles within Zinely. By applying, you
        confirm the information is accurate and that you are at least 18 years old.
      </p>

      <h2>12 · Changes to these Terms</h2>
      <p>
        We may revise these Terms occasionally. The version published at this URL is
        the operative version. Material changes that affect existing engagements will
        be communicated to active creators by email or Telegram before they take effect.
      </p>

      <h2>13 · Contact</h2>
      <p>
        Questions about these Terms can be sent to <a href="https://t.me/timzines" target="_blank" rel="noopener noreferrer">Telegram @timzines</a>{' '}
        or via the <a href="https://t.me/zinelyagency" target="_blank" rel="noopener noreferrer">Zinely Telegram group</a>.
      </p>
    </LegalLayout>
  );
}

// ─── Privacy Policy ───────────────────────────────────────────────────
function PrivacyPolicy() {
  return (
    <LegalLayout eyebrow="Legal" title="Privacy Policy" lastUpdated="27 April 2026">
      <p>
        This policy explains what personal information Zinely collects, how we use it,
        and the choices you have over it. It applies to creators who engage Zinely's
        services and to applicants for chatter roles.
      </p>

      <h2>1 · Who we are</h2>
      <p>
        Zinely is the data controller for the personal information described in this
        policy. You can reach us at{' '}<a href="https://t.me/timzines" target="_blank" rel="noopener noreferrer">Telegram @timzines</a>.
      </p>

      <h2>2 · What we collect</h2>
      <p>From <strong>creators</strong> who engage our services we collect:</p>
      <ul>
        <li>Identity and contact details (name, email, phone or messenger handle).</li>
        <li>Creator-account details (handles, platforms, niches, current revenue band).</li>
        <li>Account-access credentials and session data, where applicable.</li>
        <li>Performance and revenue data generated during the engagement (PPV unlocks, tips, subscriber metrics, DM transcripts).</li>
      </ul>
      <p>From <strong>chatter applicants</strong> we collect:</p>
      <ul>
        <li>Identity and contact details (name, email, phone, country, timezone).</li>
        <li>Background information you choose to share (years chatting, prior platforms, niches you'll work, schedule, free-text answers).</li>
      </ul>
      <p>From <strong>website visitors</strong> we collect basic technical data needed to serve the site (IP address, user-agent, page view) for security and aggregate analytics. We do not use behavioural ad-tracking cookies.</p>

      <h2>3 · How we use it</h2>
      <ul>
        <li><strong>Service delivery.</strong> Creator data is used to provide the chatting and account-management services you have engaged us for.</li>
        <li><strong>Application review.</strong> Applicant data is used to assess fit for chatter roles and to contact you about the outcome.</li>
        <li><strong>Communication.</strong> We use your contact details to respond to enquiries, send invoices, and share performance reports.</li>
        <li><strong>Legal &amp; security.</strong> We may use information to comply with legal obligations and to investigate misuse of our services.</li>
      </ul>

      <h2>4 · Who we share it with</h2>
      <p>
        We do not sell personal information. We share information only with:
      </p>
      <ul>
        <li>Zinely chatters and account managers assigned to your account, all of whom are bound by NDA.</li>
        <li>Service providers we use to run the business (hosting, email, accounting), under contract.</li>
        <li>Authorities, where we are legally required to disclose.</li>
      </ul>

      <h2>5 · Where we store it</h2>
      <p>
        Personal information is stored in access-controlled systems with encryption in
        transit and at rest. Account credentials are held in a credential vault with
        rotating sessions, IP whitelisting, and full audit logs. Access is restricted
        to the chatters and account managers assigned to your account.
      </p>

      <h2>6 · How long we keep it</h2>
      <ul>
        <li><strong>Active engagements:</strong> for the duration of the engagement plus 24 months for accounting and dispute-resolution purposes.</li>
        <li><strong>Unsuccessful applications:</strong> deleted within 6 months of the decision unless you ask us to retain them for future openings.</li>
        <li><strong>Aggregate analytics:</strong> retained indefinitely in non-identifying form.</li>
      </ul>

      <h2>7 · Your rights</h2>
      <p>
        Depending on where you live, you may have the right to access, correct, delete,
        or export the personal information we hold about you, and to object to certain
        uses. To exercise any of these rights, message <a href="https://t.me/timzines" target="_blank" rel="noopener noreferrer">@timzines</a> on Telegram.
        We respond to verified requests within 30 days.
      </p>

      <h2>8 · Children</h2>
      <p>
        Zinely's services are for adults only. We do not knowingly collect information
        from anyone under 18. If you believe we hold information about a minor, contact
        us and we will delete it.
      </p>

      <h2>9 · Changes to this policy</h2>
      <p>
        Material changes to this policy will be reflected here, with the "Last updated"
        date at the top revised. Active creators will be notified of material changes by
        Telegram or email before they take effect.
      </p>

      <h2>10 · Contact</h2>
      <p>
        Privacy questions or requests: <a href="https://t.me/timzines" target="_blank" rel="noopener noreferrer">Telegram @timzines</a>{' '}
        or via the <a href="https://t.me/zinelyagency" target="_blank" rel="noopener noreferrer">Zinely Telegram group</a>.
      </p>
    </LegalLayout>
  );
}

// ─── App shell (mirrors cases.jsx pattern) ────────────────────────────
function App() {
  useReveal();
  const tg = (window.ZINELY_CONFIG && window.ZINELY_CONFIG.telegramUrl) || 'https://t.me/timzines';
  const openTelegram = () => window.open(tg, '_blank', 'noopener,noreferrer');
  const page = window.LEGAL_PAGE || 'terms';
  return (
    <>
      <Nav onBookCall={openTelegram} />
      <main>
        {page === 'privacy' ? <PrivacyPolicy /> : <TermsOfService />}
      </main>
      <Footer />
    </>
  );
}

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
